/* Generated By:JavaCC: Do not edit this line. ast1ParserConstants.java */
package ast1;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ast1ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int COMMENT = 6;
  /** RegularExpression Id. */
  int kwArrayElm = 7;
  /** RegularExpression Id. */
  int kwArrayType = 8;
  /** RegularExpression Id. */
  int kwAssign = 9;
  /** RegularExpression Id. */
  int kwBinop = 10;
  /** RegularExpression Id. */
  int kwBoolType = 11;
  /** RegularExpression Id. */
  int kwCall = 12;
  /** RegularExpression Id. */
  int kwCallStmt = 13;
  /** RegularExpression Id. */
  int kwElse = 14;
  /** RegularExpression Id. */
  int kwFormal = 15;
  /** RegularExpression Id. */
  int kwFunc = 16;
  /** RegularExpression Id. */
  int kwIf = 17;
  /** RegularExpression Id. */
  int kwIntType = 18;
  /** RegularExpression Id. */
  int kwNewArray = 19;
  /** RegularExpression Id. */
  int kwPrint = 20;
  /** RegularExpression Id. */
  int kwReturn = 21;
  /** RegularExpression Id. */
  int kwUnop = 22;
  /** RegularExpression Id. */
  int kwVarDecl = 23;
  /** RegularExpression Id. */
  int kwVoid = 24;
  /** RegularExpression Id. */
  int kwWhile = 25;
  /** RegularExpression Id. */
  int Digit = 26;
  /** RegularExpression Id. */
  int Letter = 27;
  /** RegularExpression Id. */
  int IntLit = 28;
  /** RegularExpression Id. */
  int BoolLit = 29;
  /** RegularExpression Id. */
  int StrLit = 30;
  /** RegularExpression Id. */
  int Id = 31;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<COMMENT>",
    "\"ArrayElm\"",
    "\"ArrayType\"",
    "\"Assign\"",
    "\"Binop\"",
    "\"BoolType\"",
    "\"Call\"",
    "\"CallStmt\"",
    "\"Else\"",
    "\"Formal\"",
    "\"Func\"",
    "\"If\"",
    "\"IntType\"",
    "\"NewArray\"",
    "\"Print\"",
    "\"Return\"",
    "\"Unop\"",
    "\"VarDecl\"",
    "\"void\"",
    "\"While\"",
    "<Digit>",
    "<Letter>",
    "<IntLit>",
    "<BoolLit>",
    "<StrLit>",
    "<Id>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&&\"",
    "\"||\"",
    "\"==\"",
    "\"!=\"",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "\"!\"",
  };

}
